config/routes.rb
Rails.application.routes.draw do

  get 'users/show'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  get '/about' => 'homes#about'

  resources :posts, only: [:new, :create, :index, :show, :destroy] do
    resource :favorites, only: [:create, :destroy]
  end

  resources :comments, only: [:new, :create, :destroy]

  get 'ranks/index'

  resources :relationships, only: [:create, :destroy]

  resources :users, only: [:show, :index, :edit, :update]
  get '/users/:id/follow_index' => 'users#follow_index'
  get '/users/:id/follower_index' => 'users#follower_index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :title, presence: true
  validates :name, presence: true
  validates :platform, presence: true
  validates :genre, presence: true
  validates :thought, presence: true
  validates :evaluation, presence: true

  enum platform: {
    PlayStation4: 0,
    PlayStation5: 1,
    NintendoSwitch: 2,
    Nintendo3DS: 3,
    その他のプラットフォーム: 4
  }

  enum genre: {
    アクション: 0,
    シューティング: 1,
    レーシング: 2,
    ロールプレイング: 3,
    その他のジャンル: 4
  }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  
  def me?(user_id)
    id === user_id
  end

  def follow(follow_id)
    unless self == User.find(follow_id)
      self.relationships.find_or_create_by(follow_id: follow_id)
    end
  end

  def unfollow(follow_id)
    relationship = self.relationships.find_by(follow_id: follow_id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_in_path_for(resource)
    users_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = current_user.comments.build
    @comment.post_id = params[:post_id]
  end

  def create
    @comment = Comment.new(comment_params.merge(post_id: params[:post_id], user_id: current_user.id))
    if @comment.save
      redirect_to post_path(@comment.post)
    else
      render :new
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to users_path
  end

  private

  def comment_params
    params.require(:comment).permit(:comment, :post_id)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
  end

  def create
  end

  def index
  end

  def show
  end

  def destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true)
    @posts = @posts.page(params[:page]).reverse_order
  end

  def show
    @post = Post.find(params[:id])
    @comments = Comment.all
    @user = @post.user
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to users_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :name, :platform, :genre, :thought, :note, :evaluation, :created_at)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @user = @post.user
    following = current_user.follow(params[:follow_id])
    following.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    following = current_user.unfollow(params[:follow_id])
    following.destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = Post.all
    @post = @user.posts
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def follow_index
    @user = User.find(params[:id])
    @users = @user.followings
  end

  def follower_index
    @user = User.find(params[:id])
    @users = @user.followers
  end

  def index
    @user = current_user
    follow_user_ids = @user.followings.pluck(:id)
    @posts = Post.page(params[:page]).reverse_order
    @posts = @posts.where(user_id: follow_user_ids)
    @q = @posts.ransack(params[:q])
    @posts = @q.result(distinct: true)
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/new.html.erb
<div class="container mt-5 mb-5">

  <h2 class="row">コメント</h2>

  <div class="col mt-5">
    <% if @comment.errors.any? %>
      <% @comment.errors.full_messages.each do |message| %>
      <div class="col text-danger"><%= message %>。</div>
      <% end %>
    <% end %>
  </div>

  <%= form_with model: @comment, url: comments_path(post_id: @comment.post_id), local:true do |f| %>
    <div class="col"><%= f.text_field :comment %></div>
    <div class="col mt-5 text-center"><%= f.submit "投稿する", class:"btn btn-success" %></div>
  <% end %>

</div>

app/views/homes/about.html.erb
<div class="container mt-5 mb-5">

  <h2 class="row">アバウト</h2>

  <p class="justify-content-center d-flex mt-5 h4">
    Gamersはゲームの感想を投稿するSNSサイトです。<br>
    <%= "" %><br>
    ただ感想を投稿するだけではなく、ゲームの評価・ランキング機能も備わっているので、<br>
    <%= "" %><br>
    ゲームをプレイしようか悩んでいる方への判断材料としても利用できます。<br>
    <%= "" %><br>
    また、いいね・コメント・フォロー機能により多くのユーザーと交流することが可能で、<br>
    <%= "" %><br>
    より一層ゲームを楽しむことが出来るようになると考えています。
  </p>

</div>

app/views/homes/top.html.erb
<div class="container mt-5 mb-5">

  <h2 class="row">トップ</h2>

    <p class="justify-content-center d-flex mt-5 h4">
      ようこそ、Gamersへ！<br>
      <%= "" %><br>
      このサイトは、ゲームの感想を投稿するSNSサイトになります。<br>
      <%= "" %><br>
      利用には会員登録が必要になります。
    </p>

  <h4 class="row mt-5">新規会員登録</h4>
  <div class="col">
    <div><%= link_to "こちら", new_user_registration_path %>からサインアップしてください。</div>
  </div>

  <h4 class="row mt-5">既に登録済みの方</h4>
  <div class="col">
    <div><%= link_to "こちら", new_user_session_path %>からログインしてください。</div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gamers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div id="wrapper">
      <header class="shadow">
        <nav class="navbar navbar-expand-lg navbar-light">
          <div class="container">
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                <% if user_signed_in? %>
                  <li class="nav-item">
                    <%= link_to "ホーム", users_path, class: 'nav-link text-dark' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "マイページ", user_path(current_user.id), class: 'nav-link text-dark' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "投稿一覧", posts_path, class: 'nav-link text-dark' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "投稿", new_post_path, class: 'nav-link text-dark' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
                  </li>
                <% else %>
                  <li class="nav-item">
                    <%= link_to "トップ", root_path, class: 'nav-link text-dark' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "アバウト", about_path, class: 'nav-link text-dark' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "サインアップ", new_user_registration_path, class: 'nav-link text-dark' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </nav>
      </header>

      <%= yield %>

      <footer class="shadow-sm text-white pt-5 pb-5">
        <div class="h4 text-center">Gamers</div>
        <div class="text-center mt-3">ゲームの感想を投稿するSNSサイト</div>
      </footer>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<div class="container mt-5 mb-5">

  <h2 class="row">投稿一覧</h2>

  <div class="row mt-4">
    <%= search_form_for @q do |f| %>
    <%= f.label :name, "キーワード" %>
    <%= f.search_field :name_or_title_or_user_name_cont %>
    <%= f.submit "検索" %>
    <% end %>
  </div>

  <div class="row mt-4">
  <div class="col">
    <table class="col table table-striped">
      <thead class="text-center">
        <tr>
          <th>タイトル</th>
          <th>ゲーム名</th>
          <th>評価</th>
          <th>投稿者</th>
          <th>投稿日時</th>
        </tr>
      </thead>
      <tbody class="text-center">
        <% @posts.each do |post| %>
          <tr>
            <td><%= link_to post.title, post_path(post) %></td>
            <td><%= post.name %></td>
            <td class="post-evaluation" data-score="<%= post.evaluation %>"></td>
            <td><%= post.user.name %></td>
            <td><%= l post.created_at %></td>
          </tr>
        <% end %>
        <%= paginate @posts %>
      </tbody>
    </table>

    <script>
      $('.post-evaluation').raty({
       readOnly: true,
        score: function() {
        return $(this).attr('data-score');
        },
        starHalf: '<%= asset_path("star-half.png") %>',
        starOff: '<%= asset_path("star-off.png") %>',
        starOn: '<%= asset_path("star-on.png") %>'
        });
    </script>
  </div>
  </div>

</div>

app/views/posts/new.html.erb
<div class="container mt-5 mb-5">
  <h2 class="row">投稿ページ</h2>

  <div class="col mt-4">
    <% if @post.errors.any? %>
      <% @post.errors.full_messages.each do |message| %>
      <div class="col text-danger"><%= message %>。</div>
      <% end %>
    <% end %>
  </div>

  <%= form_with model: @post, url: posts_path, local:true do |f| %>

    <div class="field row mt-5 text-center box15">
     <label for="title" class="col">タイトル</label>
     <div class="col"><%= f.text_field :title, id:"title" %></div>
    </div>

    <div class="field row mt-3 text-center box15">
     <label for="name" class="col">ゲーム名</label>
     <div class="col"><%= f.text_field :name, id:"name" %></div>
    </div>

    <div class="field row mt-3 text-center box15">
     <label for="platform" class="col">プラットフォーム</label>
     <div class="col">
       <div>
         <%= f.radio_button :platform, :PlayStation4 %>
         <%= f.label :platform, "PlayStation4", id:"PlayStation4" %>
   			 </div>
   			 <div>
         <%= f.radio_button :platform, :PlayStation5 %>
   			   <%= f.label :platform, "PlayStation5" %>
   			 </div>
   			 <div>
         <%= f.radio_button :platform, :NintendoSwitch %>
   			   <%= f.label :platform, "NintendoSwitch" %>
   			 </div>
   			 <div>
         <%= f.radio_button :platform, :Nintendo3DS %>
   			   <%= f.label :platform, "Nintendo3DS" %>
   			 </div>
   			 <div>
         <%= f.radio_button :platform, :その他のプラットフォーム %>
   			   <%= f.label :platform, "その他のプラットフォーム" %>
   			 </div>
     </div>
    </div>

    <div class="field row mt-3 text-center box15">
     <label for="genre" class="col">ジャンル</label>
     <div class="col">
       <div>
         <%= f.radio_button :genre, :アクション %>
    			  <%= f.label :genre, "アクション" %>
    			</div>
    			<div>
         <%= f.radio_button :genre, :シューティング %>
    			  <%= f.label :genre, "シューティング" %>
    			</div>
    			<div>
         <%= f.radio_button :genre, :レーシング %>
    			  <%= f.label :genre, "レーシング" %>
    			</div>
    			<div>
         <%= f.radio_button :genre, :ロールプレイング %>
    			  <%= f.label :genre, "ロールプレイング" %>
    			</div>
    			<div>
         <%= f.radio_button :genre, :その他のジャンル %>
    			  <%= f.label :genre, "その他のジャンル" %>
    			</div>
     </div>
    </div>

    <div class="field row mt-3 text-center box15">
      <label class="col">評価</label>
      <div class="col" id="evaluate_stars">
        <script>
        $('#evaluate_stars').raty({
          starOn: "<%= asset_path('star-on.png') %>",
          starOff: "<%= asset_path('star-off.png') %>",
          starHalf: "<%= asset_path('star-half.png') %>",
          scoreName: 'post[evaluation]'
        });
        </script>
      </div>
    </div>

    <div class="field row mt-3 text-center box15">
     <label for="thought" class="col">感想</label>
     <div class="col"><%= f.text_field :thought, id:"thought" %></div>
    </div>

    <div class="field row mt-3 text-center box15">
     <label for="note" class="col">備考</label>
     <div class="col"><%= f.text_field :note, id:"note" %></div>
    </div>

    <div class="actions col text-center mt-5">
      <%= f.submit "投稿する", class:"btn btn-success" %>
    </div>

  <% end %>
</div>

app/views/posts/show.html.erb
<div class="container mt-5 mb-5">

  <h2 class="row"><%= @post.title %></h2>

  <div class="field row mt-5 text-center">
    <div class="col">投稿者</div>
    <div class="col"><%= link_to @post.user.name, user_path(@post.user) %></div>
  </div>

  <div class="field row mt-3 text-center">
    <div class="col"></div>
    <div class="col"><%= render 'relationships/follow_button', user: @user %></div>
  </div>

  <div class="field row mt-5 text-center">
    <div class="col">ゲーム名</div>
    <div class="col"><%= @post.name %></div>
  </div>

  <div class="field row mt-5 text-center">
    <div class="col">プラットフォーム</div>
  	<div class="col"><%= @post.platform %></div>
  </div>

  <div class="field row mt-5 text-center">
    <div class="col">ジャンル</div>
  	<div class="col"><%= @post.genre %></div>
  </div>

  <div class="field row mt-5 text-center">
    <div class="col">評価</div>
    <div class="post-evaluation col" data-score="<%= @post.evaluation %>"></div>
    <script>
      $('.post-evaluation').raty({
      readOnly: true,
      score: function() {
      return $(this).attr('data-score');
      },
      starHalf: '<%= asset_path("star-half.png") %>',
      starOff: '<%= asset_path("star-off.png") %>',
      starOn: '<%= asset_path("star-on.png") %>'
      });
    </script>
  </div>

  <div class="field row mt-5 text-center">
    <div class="col">感想</div>
    <div class="col"><%= @post.thought %></div>
  </div>

  <div class="field row mt-5 text-center">
    <div class="col">備考</div>
    <div class="col"><%= @post.note %></div>
  </div>

  <div class="field row mt-5 text-center">
    <div class="col">投稿日時</div>
    <div class="col"><%= l @post.created_at %></div>
  </div>

  <div class="field row mt-5 text-center">
    <div class="col">コメント</div>
    <% if @comments.count == 0 %>
      <div class="col">コメントはありません。</div>
    <% else %>
      <div class="col">
        <% @comments.each do |comment| %>
          <% if current_user.id == comment.user_id %>
            <div class="col justify-content-center d-flex">
              <div><%= comment.comment %></div>
              <div><%= link_to "　コメント削除", comment_path(comment), method: :delete %></div>
            </div>
          <% else %>
            <div><%= comment.comment %></div>
            <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="field row mt-3 text-center">
    <div class="col"></div>
    <div class="col"><%= link_to "コメントする", new_comment_path(post_id: @post.id), class:"btn btn-success" %></div>
  </div>

  <div class="actions col text-center mt-5">
    <% if current_user.id == @post.user_id %>
      <div><%= link_to "投稿削除", post_path(@post), method: :delete, class:"btn btn-danger" %></div>
    <% end %>
  </div>

</div>

app/views/posts/show.js.erb
$("#like-button-zone_<%= @follow_user.id %>").html("<%= j(render partial: 'likes/like', locals: { user: @user }) %>");
$(".like_balance").html("<%= @sending_user.like_balance %>")

app/views/relationships/_follow_button.html.erb
<div id="like-button">
  <% unless current_user == user %>
    <% if current_user.following?(user) %>
      <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }, remote: true) do |f| %>
        <%= hidden_field_tag :follow_id, @post.user_id %>
        <%= hidden_field_tag :post_id, @post.id %>
        <div><%= f.submit 'フォロー解除', class: 'btn btn-danger' %></div>
      <% end %>
    <% else %>
      <%= form_for(current_user.relationships.build, remote: true) do |f| %>
        <%= hidden_field_tag :follow_id, @post.user_id %>
        <%= hidden_field_tag :post_id, @post.id %>
        <div><%= f.submit 'フォローする', class: 'btn btn-primary' %></div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/relationships/create.js.erb
$("#like-button").html("<%= j(render partial: 'relationships/follow_button', locals: { user: @user }) %>");

app/views/relationships/destroy.js.erb
$("#like-button").html("<%= j(render partial: 'relationships/follow_button', locals: { user: @user }) %>");

app/views/users/edit.html.erb
<div class="container mt-5 mb-5">

  <h2 class="row">ユーザー名変更</h2>

  <%= form_with model:@user, local:true do |f| %>
    <div class="field row mt-5 text-center box15">
      <label for="inputName" class="col">ユーザー名</label>
      <div class="col"><%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"ユーザー名"%></div>
    </div>
    <div class="col mt-5 text-center"><%= f.submit "変更を保存", class:"btn btn-success" %></div>
  <% end %>

</div>

app/views/users/follow_index.html.erb
<div class="container mt-5 mb-5">

  <h2 class="row">フォローユーザー</h2>

  <div class="row mt-4">
  <div class="col">
    <table class="col table table-striped">
      <thead>
        <tr>
          <th>ユーザー名</th>
          <th>投稿数</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td>
            <%= link_to user.name, user_path(user) %>
          </td>
          <td>
            <%= user.posts.count %>件
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  </div>

</div>

app/views/users/follower_index.html.erb
<div class="container mt-5 mb-5">

  <h2 class="row">フォロワーユーザー</h2>

  <div class="row mt-4">
  <div class="col">
    <table class="col table table-striped">
      <thead>
        <tr>
          <th>ユーザー名</th>
          <th>投稿数</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td>
            <%= link_to user.name, user_path(user) %>
          </td>
          <td>
            <%= user.posts.count %>件
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  </div>

</div>

app/views/users/index.html.erb
<div class="container mt-5 mb-5">

  <h2 class="row">ホーム</h2>

  <div class="row mt-4">
    <%= search_form_for @q, url: users_path do |f| %>
    <%= f.label :name, "キーワード" %>
    <%= f.search_field :name_or_title_or_user_name_cont %>
    <%= f.submit "検索" %>
    <% end %>
  </div>

  <div class="row mt-4 text-center">
  <div class="col">
    <table class="col table table-striped">
      <thead>
        <tr>
          <th>タイトル</th>
          <th>ゲーム名</th>
          <th>評価</th>
          <th>投稿者</th>
          <th>投稿日時</th>
        </tr>
      </thead>
      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td><%= link_to post.title, post_path(post) %></td>
            <td><%= post.name %></td>
            <td class="post-evaluation" data-score="<%= post.evaluation %>"></td>
            <td><%= post.user.name %></td>
            <td><%= l post.created_at %></td>
          </tr>
        <% end %>
        <%= paginate @posts %>
      </tbody>
    </table>

    <script>
      $('.post-evaluation').raty({
       readOnly: true,
        score: function() {
        return $(this).attr('data-score');
        },
        starHalf: '<%= asset_path("star-half.png") %>',
        starOff: '<%= asset_path("star-off.png") %>',
        starOn: '<%= asset_path("star-on.png") %>'
        });
    </script>
  </div>
  </div>

</div>

app/views/users/show.html.erb
<div class="container mt-5 mb-5">

  <h2 class="row">ユーザー情報</h2>

  <div class="field row mt-5 text-center">
    <div class="col">ユーザー名</div>
    <div class="col"><%= @user.name %></div>
  </div>

  <% if @user.me?(current_user.id) %>
  <div class="row mt-3 text-center">
    <div class="col"></div>
    <div class="col"><%= link_to "ユーザー名変更", edit_user_path(@user), class:"btn btn-success" %></div>
  </div>
  <% end %>

  <div class="field row mt-4 text-center">
    <div class="col">フォロー中</div>
    <% if @user.followings.count == 0 %>
      <div class="col"><%= @user.followings.count %>人</div>
    <% else %>
      <div class="col"><%= link_to @user.followings.count, controller: "users", action: "follow_index", id: @user %>人</div>
    <% end %>
  </div>

  <div class="field row mt-4 text-center">
    <div class="col">フォロワー</div>
    <% if @user.followers.count == 0 %>
      <div class="col"><%= @user.followers.count %>人</div>
    <% else %>
      <div class="col"><%= link_to @user.followers.count, controller: "users", action: "follower_index", id: @user %>人</div>
    <% end %>
  </div>

  <div class="col mt-5 h4">投稿一覧</div>
    <% if @post.count == 0 %>
      <div class="col mt-4">投稿はありません。</div>
    <% else %>
      <div class="col">
        <table class="col table table-striped mt-4">
          <thead>
            <tr>
              <th>タイトル</th>
              <th>ゲーム名</th>
              <th>評価</th>
              <th>投稿日時</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @user.posts.each do |post| %>
            <tr>
              <td><%= link_to post.title, post_path(post) %></td>
              <td><%= post.name %></td>
              <td class="post-evaluation" data-score="<%= post.evaluation %>"></td>
              <td><%= l post.created_at %></td>
              <% if current_user.id == @user.id %>
                <td><%= link_to "投稿削除", post_path(post), method: :delete, class:"btn btn-danger" %></td>
              <% else %>
                <td></td>
              <% end %>
            </tr>
            <% end %>
          </tbody>
        </table>

        <script>
          $('.post-evaluation').raty({
           readOnly: true,
            score: function() {
            return $(this).attr('data-score');
            },
            starHalf: '<%= asset_path("star-half.png") %>',
            starOff: '<%= asset_path("star-off.png") %>',
            starOn: '<%= asset_path("star-on.png") %>'
            });
        </script>
      </div>
    <% end %>

</div>